httpPort: 8090
grpcPort: 8091
imageFolder: ./images/
compressImageFolder: ./compress-images/
discovery:
  eureka:
    url: http://admin:admin@localhost:8761/eureka
ssl:
  enabled: false
  caCert: certs/trustCertCollectionFile.crt
  serverCert: certs/certChainFile.crt
  serverKey: certs/privateKeyFile.key
mailService:
    host: smtp.ethereal.email
    port: 587
    sender: admin-vizcentric@gmail.com
    testUser: admin@vizcentric.com
    auth :
      user: rudolph.schoen@ethereal.email
      pass:
grpc:
  auth:
    username: flair-notifications
    jwtKey: secretKey1secretKey1secretKey1secretKey1secretKey1secretKey1secretKey1